### ISSUE TITLE
Use mozlog format

### ISSUE THREAD

**Issue by clouserw** [mozilla/watchdog-proxy#196]
We should emit logs in the mozlog format.  The documentation I could find is at https://wiki.mozilla.org/Firefox/Services/Logging

**Comment by lmorchard** [comment]
Looks like there's an npm module to take care of the format: https://www.npmjs.com/package/mozlog

Not entirely clear on *what* to log, since what we do so far is mostly debugging output. Could basically log the same things we send out for metrics pings and/or what we will send out for Sentry, but that seems redundant.

**Comment by lmorchard** [comment]
Also, CloudWatch captures the raw console.log() calls as events - so there's some stuff in there that we can't force into a mozlog format. (e.g. start & end of API gateway calls, warnings from Sentry, etc)

Wondering if maybe there's a better destination for logs? (i.e. some service to post them at, etc)

**Comment by lmorchard** [comment]
[I guess what we really need here is a `LOGGING.md` like we have a `METRICS.md`](https://github.com/mozilla/fxa-auth-server/blob/master/docs/api.md#defined-errors) - not just a simple log format change
