### ISSUE TITLE
Implement metrics pings

### ISSUE THREAD

**Issue by lmorchard** [mozilla/watchdog-proxy#47]
From the PRD:

> Workflow 3: Statistics
>
> To track the performance and effectiveness of this API, some statistics will be available to administrators:
>
> Lag time from submission to Watchdog (step 1) and submission to PhotoDNA (step 3).
> Processing time from Microsoft (i.e. step 3 to step 4c)
> Statistics about the size of the message queue, both currently and historically.
> Numbers of positives that have not been reviewed and are under review.
> Total numbers of images processed.
>
> Each of these should be available globally, as well as broken down per consumer application.

**Comment by lmorchard** [comment]
See also: https://github.com/mozilla/ping-centre/issues/130

**Comment by chenba** [comment]
Now that the cement has mostly dried, there are a couple potential issues in the [Metrics doc](https://github.com/mozilla/watchdog-proxy/blob/master/docs/metrics.md) I want to mention.  (Paging @clouserw)

In the "worker_works" event, there's a "is_error" field.  It's for tracking error responses from PhotoDNA.  Do we care about any other error states?  I assume we'd still submit a ping even if we do not receive a valid response or Lambda times out (although I don't know if the function would get a chance to do anything in that scenario).

In the "worker_sleeps" event, the "items_in_queue" number is reported.  However, when the queue poller exits, the message processors, which actually remove messages from the queue, might still be running.  There's a mechanism to ensure only one poller runs but nothing to have the poller wait for all of its processors to finish (we wouldn't want that anyway).  Unless the number of we are interested in is number of message in the queue subtract the number of processors the poller started?  Otherwise, it's more accurate to count the number of "worker_works" events in a time interval where "is_error" is false to get the some kind of throughput figure.

**Comment by chenba** [comment]
Oh "worker_sleeps" already have a "items_processed"...so ignore my question above about number of message processor started.  The "items_in_queue" field is still questionable though.

**Comment by wresuolc** [comment]
I think if there is an error in Watchdog or PhotoDNA, we don't send a reply to the consumer at all.  We can requeue it if possible, or else we drop it and the client sees that it never got an answer to it and re-sends it later.  That's just my first reaction, open to input on it.

@chenba I think I like your ideas for querying SQS.  Can you make a patch for metrics.md?

**Comment by chenba** [comment]
> We can requeue it if possible, or else we drop it and the client sees that it never got an answer to it and re-sends it later.

Re-queues/re-tries are automatic: if the message is not deleted within 60 seconds, it'll be visible in the queue again.  Ten processing attempts will be made before a message is moved to the DLQ.

Side note: with our current configuration, there is small chance of double processing a message.  The message visibility timeout and the processor lambda timeout are both set to 60 seconds.  There's a _tiny_ window where the message could become visible again, _and_ picked up by the queue poller, before the processor delete it.

**Comment by wresuolc** [comment]
Double processing isn't a big deal, I think

**Comment by lmorchard** [comment]
Now that I'm finally running through this to implement, I'm finding some measurements that maybe don't make sense.

* The `pollQueue` function doesn't awake or sleep on demand. It starts up every 60 seconds and runs continually until exiting just before the next startup - a hack to workaround AWS not supporting persistent long-running functions. 

  So, we can send a `worker_awakes` on startup and `worker_sleeps` on exit every 60s - is that often enough for good queue metrics? 

* `pollQueue` does many long poll fetches over 60s with varying numbers of items requested based on rate limit. So, the single `items_to_claim` at startup doesn't make sense. But, I don't think we want to send a metrics ping for every long poll from the queue.

* The `processQueueItem` function is a good spot to fire `worker_works` pings, but there's no `timing_retrieved` per queue item fetched. The `pollQueue` function fetches items in batches and invokes a function for each item in the batch. So, they arrive basically pre-fetched in the worker.

**Comment by lmorchard** [comment]
Been starting to implement metrics pings... Per my last comment, [I'm proposing some changes to metrics.md to better reflect actual functionality](https://github.com/mozilla/watchdog-proxy/pull/75/files#diff-683a405c5c005542f9e848b827fe0765).
