### ISSUE TITLE
Add Integer ID for Consumers

### ISSUE THREAD

**Issue by chenba** [mozilla/watchdog-proxy#58]
The [Metrics doc](https://github.com/mozilla/watchdog-proxy/blob/master/docs/metrics.md) mentions an integer "consumer_id".  This is currently not in the `credentials` DynamoDB table.

**Comment by lmorchard** [comment]
Oh, yeah, good catch! Actually, @clouserw, would it make sense to just make this a "consumer_name" string rather than an integer? This isn't a SQL db table with an auto-increment ID, so whomever adds credentials to the table is doing it by hand and will need to come up with a value. Might work better to use something more human-meaningful

**Comment by wresuolc** [comment]
ha, I debated using name or ID.  Sure, let's go with name.  Can you patch metrics.md also?
